"""Publish generated blog posts to the Portfolio API."""

import os
import requests


def check_duplicate(title):
    """Check if a post with similar title already exists."""
    api_url = os.getenv("PORTFOLIO_API_URL")
    try:
        res = requests.post(
            f"{api_url}/automation/posts/check-duplicate",
            json={"title": title},
            timeout=10
        )
        data = res.json()
        return data.get("is_duplicate", False)
    except Exception as e:
        print(f"Duplicate check failed: {e}")
        return True  # Assume duplicate on error (safe default)


def publish_post(post_data):
    """Publish a post via the automation API."""
    api_url = os.getenv("PORTFOLIO_API_URL")
    api_token = os.getenv("PORTFOLIO_API_TOKEN")

    if not api_token:
        print("ERROR: PORTFOLIO_API_TOKEN not set")
        return False

    headers = {
        "Authorization": f"Bearer {api_token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    payload = {
        "title": post_data["title"],
        "content": post_data["content"],
        "excerpt": post_data.get("excerpt", ""),
        "meta_title": post_data.get("meta_title", post_data["title"]),
        "meta_description": post_data.get("meta_description", ""),
        "tags": post_data.get("tags", ""),
        "published": True,
        "published_at": None,  # Publish immediately
    }

    try:
        res = requests.post(
            f"{api_url}/automation/posts",
            json=payload,
            headers=headers,
            timeout=30
        )

        if res.status_code in (200, 201):
            data = res.json()
            print(f"Published: {post_data['title']} (ID: {data.get('data', {}).get('id', 'N/A')})")
            return True
        else:
            print(f"Publish failed ({res.status_code}): {res.text[:200]}")
            return False
    except Exception as e:
        print(f"Publish error: {e}")
        return False


if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    # Test with a sample post
    test_post = {
        "title": "Test Auto-Generated Post",
        "content": "<p>This is a test post generated by the auto-blog service.</p>",
        "excerpt": "A test of the auto-blog publishing pipeline.",
        "meta_title": "Test Auto Post",
        "meta_description": "Testing auto-blog publishing",
        "tags": "test,automation"
    }

    if not check_duplicate(test_post["title"]):
        publish_post(test_post)
    else:
        print("Post already exists (duplicate)")
